linters:
  enable-all: true
  disable:
    - errcheck
    - depguard
    - varnamelen
    - nosnakecase
    - tparallel
    - paralleltest
    - goerr113
    - wrapcheck
    - nlreturn
    - gomnd
    - exhaustivestruct
    - exhaustruct
