name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: run Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Test All
        run: go test -v ./...
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build
        run: go build -v ./...
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install tools
        run: |
          go get golang.org/x/tools/cmd/gofmt
          go get mvdan.cc/gofumpt/gofumports
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
          go install golang.org/x/tools/cmd/gofmt
          go install mvdan.cc/gofumpt/gofumports
          go install github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Format code
        run: gofumports -w -l -local ./ .

      - name: Lint code
        run: golangci-lint run --config .golangci.yml
